{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-sanitization.secretName" . }}
  labels:
    {{- include "data-sanitization.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey }}
{{- end }}
